name: Create Test Environment

on:
  pull_request:
    branches:
      - master

jobs:
  create-infra:
    name: Setup Infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure/pr-module
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'eu-west-1'
    steps:
      - uses: actions/checkout@v2
      - run: echo "::set-env name=BRANCH_NAME::${{ github.head_ref }}"
      - run: terraform init
      - run: terraform workspace select $BRANCH_NAME || terraform workspace new $BRANCH_NAME
      - run: terraform apply -var="branch_name=$BRANCH_NAME" -auto-approve

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: create-infra
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', 
          github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install
      - name: Generate static
        run: yarn generate
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: acid-web-${{ github.head_ref }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-1'
          SOURCE_DIR: './dist'
      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        id: deployment
        with:
          token: '${{ github.token }}'
          target_url: http://acid-web-${{ github.head_ref }}.s3-website-eu-
          west-1.amazonaws.com
          environment: ${{ github.head_ref }}
          initial_status: success
          ref: ${{ github.event.pull_request.head.sha }}
